### PR TITLE
refactor(all): update repo structure (2)

### PR DESCRIPTION
**Pull request by devanp92**
Finish linting all files except index.js (has console statements) and nodejs-mutation-emulator.js.

Hopefully, this can be included in your [PR](https://github.com/aurelia/pal-nodejs/pull/3).

### CODE REVIEW

**Comment by martingust** [comment]
@devanp92 Nice! `dist` can't be in the `.gitignore`-file though. The dist files need to be included in the release commits. Can you update that and I'll get this merged. 

Thanks!

**Comment by martingust** [comment]
@devanp92 I pushed another commit to my branch, please rebase with latest.

**Comment by devanp92** [comment]
@martingust Rebased. (May have gotten botched, but please let me know if it needs anything else).

**Comment by martingust** [comment]
@devanp92 Sorry my clumsy explanation.  The dist files should only be included in a release commit like [this](https://github.com/aurelia/ui-virtualization/commit/0fbca57a04b5612b6c19e286c4d50e62bf2f2638). All other commits should only include the source files. Again sorry about that.

**Comment by devanp92** [comment]
@martingust No problem! Updated.

**Pull request closed without merging**
